spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/rmt-platform?currentSchema=schema_auth&stringtype=unspecified
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: schema_auth
    liquibase-schema: schema_auth

# Минимизируем логирование в контейнерах
logging:
  level:
    root: INFO
    ru.practicum: INFO
    ru.practicum.auth: WARN