spring:
  datasource:
    # Локально подключаемся к localhost, а не к контейнеру
    url: jdbc:postgresql://localhost:5432/rmt-platform?currentSchema=${spring.jpa.properties.hibernate.default_schema}&stringtype=unspecified

  # Включаем вывод SQL для отладки
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Отключаем строгие таймауты для локальной разработки
feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000

jwt:
  secret:
    access: ${JWT_ACCESS_SECRET}
  expiration:
    access:
      minutes: 1440   # 24 часа

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG