server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://postgres:5432/rmt-platform?currentSchema=schema_auth
    username: ${SPRING_DATASOURCE_USERNAME:rmt_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:change_me}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: schema_auth
        jdbc:
          batch_size: 20

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: schema_auth
    liquibase-schema: schema_auth
    drop-first: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: when_authorized

jwt:
  secret:
    access: ${JWT_ACCESS_SECRET}
  expiration:
    access:
      minutes: 1440   # 24 часа

logging:
  level:
    root: INFO
    ru.practicum.auth: DEBUG


