spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/rmt-platform?currentSchema=${spring.jpa.properties.hibernate.default_schema}&stringtype=unspecified

# Более строгие таймауты для prod-подобной среды
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

jwt:
  secret:
    access: ${JWT_ACCESS_SECRET}
  expiration:
    access:
      minutes: 1440   # 24 часа

# Минимизируем логирование в контейнерах
logging:
  level:
    root: INFO
    ru.practicum: INFO