spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/testdb
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: schema_control

  liquibase:
    enabled: false  # Отключаем liquibase для тестов