server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/rmt-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always

logging.level.org.mapstruct=TRACE

# ????? ????????? ??????? ????
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.format.date-time=yyyy-MM-dd HH:mm:ss