CREATE TABLE IF NOT EXISTS aggregates (
    aggregate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    type VARCHAR(50) NOT NULL,
    has_temperature_sensors BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS temperature_readings (
    temperature_reading_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id BIGINT NOT NULL REFERENCES aggregates(aggregate_id) ON DELETE CASCADE,
    reading_date TIMESTAMP NOT NULL,
    front_bearing_temp DECIMAL(5,2),
    rear_bearing_temp DECIMAL(5,2),
    warning_triggered BOOLEAN NOT NULL,
    alarm_triggered BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS thresholds (
    threshold_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id BIGINT NOT NULL REFERENCES aggregates(aggregate_id) ON DELETE CASCADE,
    warning_threshold DECIMAL(5,2),
    warning_timestamp TIMESTAMP NOT NULL,
    alarm_threshold DECIMAL(5,2),
    alarm_timestamp TIMESTAMP NOT NULL
);