spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/rmt-platform?currentSchema=schema_monitoring&stringtype=unspecified
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: schema_monitoring
    liquibase-schema: schema_monitoring

# Более строгие таймауты для prod-подобной среды
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

# Минимизируем логирование в контейнерах
logging:
  level:
    root: INFO
    ru.practicum: INFO
    ru.practicum.monitoring: DEBUG